# Generated by Django 3.2.7 on 2021-09-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'verbose_name_plural': 'CustomerAddresses'},
        ),
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name_plural': 'OrderProducts'},
        ),
    ]
